"""Agrega campo historial_atraso a Cliente

Revision ID: 0ec5e2ddc95c
Revises: 
Create Date: 2025-05-27 19:07:55.332601

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ec5e2ddc95c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historial_atraso', sa.Integer(), nullable=True))

    with op.batch_alter_table('creditos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('creditos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('historial_atraso')

    # ### end Alembic commands ###
