"""Add unique constraint to pagos

Revision ID: a45131f133d4
Revises: 0ec5e2ddc95c
Create Date: 2025-06-24 19:58:43.650050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a45131f133d4'
down_revision = '0ec5e2ddc95c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.drop_column('historial_atraso')

    with op.batch_alter_table('creditos', schema=None) as batch_op:
        batch_op.drop_column('estado')

    with op.batch_alter_table('pagos', schema=None) as batch_op:
        #batch_op.create_unique_constraint('unique_pago_credito_cuota', ['num_credito', 'num_cuota'])
        pass

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pagos', schema=None) as batch_op:
        batch_op.drop_constraint('unique_pago_credito_cuota', type_='unique')

    with op.batch_alter_table('creditos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('estado', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('clientes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('historial_atraso', sa.INTEGER(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
